/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author equipo hp
 */
public class ViewPeliculas extends javax.swing.JPanel {

    /**
     * Creates new form ViewPeliculas
     */
    public ViewPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1_MODIFICAR = new javax.swing.JButton();
        jTextField2_ID_PELICULA = new javax.swing.JTextField();
        jTextField4_FORMATO = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jButton3_Eliminar = new javax.swing.JButton();
        jLabel5_duracion = new javax.swing.JLabel();
        jButton_anterior = new javax.swing.JButton();
        jTextField2_NOMBRE = new javax.swing.JTextField();
        jTextField3_GENERO = new javax.swing.JTextField();
        jTextField5_DURACION = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton_siguiente = new javax.swing.JButton();
        jButton1_nuevo = new javax.swing.JButton();
        jButton_ultimo = new javax.swing.JButton();
        jButton_primero = new javax.swing.JButton();
        jLabel2_nombre = new javax.swing.JLabel();
        jButton1_Almacenar = new javax.swing.JButton();
        jLabel3_genero = new javax.swing.JLabel();
        jButton2_Modificar = new javax.swing.JButton();
        jLabel4_formato = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_id_pelicula = new javax.swing.JTextField();
        jcb_formato = new javax.swing.JComboBox<>();

        jButton1_MODIFICAR.setText("MODIFICAR");
        jButton1_MODIFICAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_MODIFICARMouseClicked(evt);
            }
        });
        jButton1_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_MODIFICARActionPerformed(evt);
            }
        });

        jTextField2_ID_PELICULA.setEditable(false);
        jTextField2_ID_PELICULA.setEnabled(false);
        jTextField2_ID_PELICULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_ID_PELICULAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jButton3_Eliminar.setText("Eliminar");
        jButton3_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_EliminarMouseClicked(evt);
            }
        });

        jLabel5_duracion.setText("duracion");

        jButton_anterior.setText("<<");
        jButton_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_anteriorMouseClicked(evt);
            }
        });

        jLabel10.setText("            PELICULAS");

        jButton_siguiente.setText(">>");
        jButton_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_siguienteMouseClicked(evt);
            }
        });

        jButton1_nuevo.setText("Nuevo");
        jButton1_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_nuevoMouseClicked(evt);
            }
        });

        jButton_ultimo.setText(">|");
        jButton_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ultimoMouseClicked(evt);
            }
        });

        jButton_primero.setText("|<");
        jButton_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_primeroMouseClicked(evt);
            }
        });

        jLabel2_nombre.setText("nombre");

        jButton1_Almacenar.setText("Almacenar");
        jButton1_Almacenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_AlmacenarMouseClicked(evt);
            }
        });

        jLabel3_genero.setText("genero");

        jButton2_Modificar.setText("Modificar");
        jButton2_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_ModificarMouseClicked(evt);
            }
        });

        jLabel4_formato.setText("formato");

        jLabel1.setText("id_pelicula");

        jcb_formato.setBackground(new java.awt.Color(102, 102, 102));
        jcb_formato.setFont(new java.awt.Font("PakType Naskh Basic", 1, 24)); // NOI18N
        jcb_formato.setForeground(new java.awt.Color(255, 255, 255));
        jcb_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DVD", "Blu-ray" }));
        jcb_formato.setAlignmentX(0.0F);
        jcb_formato.setAlignmentY(0.0F);
        jcb_formato.setDoubleBuffered(true);
        jcb_formato.setMaximumSize(new java.awt.Dimension(200, 40));
        jcb_formato.setMinimumSize(new java.awt.Dimension(200, 40));
        jcb_formato.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton1_nuevo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_primero)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton_siguiente)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_ultimo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5_DURACION, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3_GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1_Almacenar)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2_Modificar)
                            .addGap(37, 37, 37)
                            .addComponent(jButton3_Eliminar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_id_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2_nombre))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jLabel3_genero)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4_formato)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3_GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5_duracion)
                    .addComponent(jTextField5_DURACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_primero)
                    .addComponent(jButton_anterior)
                    .addComponent(jButton_siguiente)
                    .addComponent(jButton_ultimo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3_Eliminar)
                    .addComponent(jButton2_Modificar)
                    .addComponent(jButton1_Almacenar))
                .addGap(18, 18, 18)
                .addComponent(jButton1_nuevo)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_EliminarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3_EliminarMouseClicked

    private void jButton_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_anteriorMouseClicked
       
    }//GEN-LAST:event_jButton_anteriorMouseClicked

    private void jButton1_MODIFICARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_MODIFICARMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1_MODIFICARMouseClicked

    private void jButton1_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_MODIFICARActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_MODIFICARActionPerformed

    private void jButton_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_siguienteMouseClicked
        
    }//GEN-LAST:event_jButton_siguienteMouseClicked

    private void jButton1_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_nuevoMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1_nuevoMouseClicked

    private void jButton_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ultimoMouseClicked
      
    }//GEN-LAST:event_jButton_ultimoMouseClicked

    private void jButton_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_primeroMouseClicked
    
    }//GEN-LAST:event_jButton_primeroMouseClicked

    private void jTextField2_ID_PELICULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_ID_PELICULAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_ID_PELICULAActionPerformed

    private void jButton1_AlmacenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_AlmacenarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1_AlmacenarMouseClicked

    private void jButton2_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_ModificarMouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jButton2_ModificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1_Almacenar;
    public javax.swing.JButton jButton1_MODIFICAR;
    public javax.swing.JButton jButton1_nuevo;
    public javax.swing.JButton jButton2_Modificar;
    public javax.swing.JButton jButton3_Eliminar;
    public javax.swing.JButton jButton_anterior;
    public javax.swing.JButton jButton_primero;
    public javax.swing.JButton jButton_siguiente;
    public javax.swing.JButton jButton_ultimo;
    private javax.swing.JDesktopPane jDesktopPane2;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel2_nombre;
    public javax.swing.JLabel jLabel3_genero;
    public javax.swing.JLabel jLabel4_formato;
    public javax.swing.JLabel jLabel5_duracion;
    public javax.swing.JTextField jTextField1_id_pelicula;
    private javax.swing.JTextField jTextField2_ID_PELICULA;
    public javax.swing.JTextField jTextField2_NOMBRE;
    public javax.swing.JTextField jTextField3_GENERO;
    public javax.swing.JTextField jTextField4_FORMATO;
    public javax.swing.JTextField jTextField5_DURACION;
    public javax.swing.JComboBox<String> jcb_formato;
    // End of variables declaration//GEN-END:variables
}
