/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author equipo hp
 */
public class ViewClientes extends javax.swing.JPanel {

    /**
     * Creates new form ViewClientes
     */
    public ViewClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_siguiente = new javax.swing.JButton();
        jButton1_nuevo = new javax.swing.JButton();
        jButton_ultimo = new javax.swing.JButton();
        jButton3_Eliminar = new javax.swing.JButton();
        jButton_primero = new javax.swing.JButton();
        jButton_anterior = new javax.swing.JButton();
        jButton1_Almacenar = new javax.swing.JButton();
        jButton2_Modificar = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_id_cliente = new javax.swing.JTextField();
        jTextField2_nombre = new javax.swing.JTextField();
        jTextField3_telefono = new javax.swing.JTextField();
        jTextField4_email = new javax.swing.JTextField();
        jTextField5_direccion = new javax.swing.JTextField();
        jButton_siguiente1 = new javax.swing.JButton();
        jButton1_nuevo1 = new javax.swing.JButton();
        jButton_ultimo1 = new javax.swing.JButton();
        jButton3_Eliminar1 = new javax.swing.JButton();
        jButton_primero1 = new javax.swing.JButton();
        jButton_anterior1 = new javax.swing.JButton();
        jButton1_Almacenar1 = new javax.swing.JButton();
        jButton2_Modificar1 = new javax.swing.JButton();

        jButton_siguiente.setText(">>");
        jButton_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_siguienteMouseClicked(evt);
            }
        });

        jButton1_nuevo.setText("Nuevo");
        jButton1_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_nuevoMouseClicked(evt);
            }
        });

        jButton_ultimo.setText(">|");
        jButton_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ultimoMouseClicked(evt);
            }
        });

        jButton3_Eliminar.setText("Eliminar");
        jButton3_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_EliminarMouseClicked(evt);
            }
        });

        jButton_primero.setText("|<");
        jButton_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_primeroMouseClicked(evt);
            }
        });

        jButton_anterior.setText("<<");
        jButton_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_anteriorMouseClicked(evt);
            }
        });

        jButton1_Almacenar.setText("Almacenar");
        jButton1_Almacenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_AlmacenarMouseClicked(evt);
            }
        });

        jButton2_Modificar.setText("Modificar");
        jButton2_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_ModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jLabel1.setText("     CLIENTES");

        jLabel2.setText("id_cliente");

        jLabel3.setText("nombre");

        jLabel4.setText("telefono");

        jLabel5.setText("email");

        jLabel6.setText("direccion");

        jButton_siguiente1.setText(">>");
        jButton_siguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_siguiente1MouseClicked(evt);
            }
        });

        jButton1_nuevo1.setText("Nuevo");
        jButton1_nuevo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_nuevo1MouseClicked(evt);
            }
        });

        jButton_ultimo1.setText(">|");
        jButton_ultimo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ultimo1MouseClicked(evt);
            }
        });

        jButton3_Eliminar1.setText("Eliminar");
        jButton3_Eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_Eliminar1MouseClicked(evt);
            }
        });

        jButton_primero1.setText("|<");
        jButton_primero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_primero1MouseClicked(evt);
            }
        });

        jButton_anterior1.setText("<<");
        jButton_anterior1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_anterior1MouseClicked(evt);
            }
        });

        jButton1_Almacenar1.setText("Almacenar");
        jButton1_Almacenar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_Almacenar1MouseClicked(evt);
            }
        });

        jButton2_Modificar1.setText("Modificar");
        jButton2_Modificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_Modificar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3_telefono)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField4_email, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField5_direccion)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1_id_cliente)
                                    .addComponent(jTextField2_nombre)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jButton1_nuevo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_primero1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_anterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton_siguiente1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_ultimo1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1_Almacenar1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2_Modificar1)
                                .addGap(37, 37, 37)
                                .addComponent(jButton3_Eliminar1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_primero1)
                    .addComponent(jButton_anterior1)
                    .addComponent(jButton_siguiente1)
                    .addComponent(jButton_ultimo1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3_Eliminar1)
                    .addComponent(jButton2_Modificar1)
                    .addComponent(jButton1_Almacenar1))
                .addGap(18, 18, 18)
                .addComponent(jButton1_nuevo1)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_siguienteMouseClicked

    }//GEN-LAST:event_jButton_siguienteMouseClicked

    private void jButton1_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_nuevoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1_nuevoMouseClicked

    private void jButton_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ultimoMouseClicked

    }//GEN-LAST:event_jButton_ultimoMouseClicked

    private void jButton3_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_EliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_EliminarMouseClicked

    private void jButton_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_primeroMouseClicked

    }//GEN-LAST:event_jButton_primeroMouseClicked

    private void jButton_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_anteriorMouseClicked

    }//GEN-LAST:event_jButton_anteriorMouseClicked

    private void jButton1_AlmacenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_AlmacenarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1_AlmacenarMouseClicked

    private void jButton2_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_ModificarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2_ModificarMouseClicked

    private void jButton_siguiente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_siguiente1MouseClicked

    }//GEN-LAST:event_jButton_siguiente1MouseClicked

    private void jButton1_nuevo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_nuevo1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1_nuevo1MouseClicked

    private void jButton_ultimo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ultimo1MouseClicked

    }//GEN-LAST:event_jButton_ultimo1MouseClicked

    private void jButton3_Eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_Eliminar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_Eliminar1MouseClicked

    private void jButton_primero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_primero1MouseClicked

    }//GEN-LAST:event_jButton_primero1MouseClicked

    private void jButton_anterior1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_anterior1MouseClicked

    }//GEN-LAST:event_jButton_anterior1MouseClicked

    private void jButton1_Almacenar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_Almacenar1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1_Almacenar1MouseClicked

    private void jButton2_Modificar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_Modificar1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2_Modificar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1_Almacenar;
    public javax.swing.JButton jButton1_Almacenar1;
    public javax.swing.JButton jButton1_nuevo;
    public javax.swing.JButton jButton1_nuevo1;
    public javax.swing.JButton jButton2_Modificar;
    public javax.swing.JButton jButton2_Modificar1;
    public javax.swing.JButton jButton3_Eliminar;
    public javax.swing.JButton jButton3_Eliminar1;
    public javax.swing.JButton jButton_anterior;
    public javax.swing.JButton jButton_anterior1;
    public javax.swing.JButton jButton_primero;
    public javax.swing.JButton jButton_primero1;
    public javax.swing.JButton jButton_siguiente;
    public javax.swing.JButton jButton_siguiente1;
    public javax.swing.JButton jButton_ultimo;
    public javax.swing.JButton jButton_ultimo1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JTextField jTextField1_id_cliente;
    public javax.swing.JTextField jTextField2_nombre;
    public javax.swing.JTextField jTextField3_telefono;
    public javax.swing.JTextField jTextField4_email;
    public javax.swing.JTextField jTextField5_direccion;
    // End of variables declaration//GEN-END:variables
}
